server:
  port: 9999
  context-path: /uaa
security:
  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG

spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    sentinel:
      master: localhost # Name of the Redis Server
      nodes: 127.0.0.1:6379  # Comma separated list of host:port
    timeout: 0

