server:
  port: 8888

security:
  sessions: ALWAYS
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user
zuul:
  routes:
    ui:
      url: http://localhost:8081
    admin:
      url: http://localhost:8082
#    user:
#      path: /user/**
#      url: http://localhost:9999/uaa/user
    resource:
      url: http://localhost:9000